import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import MenuBar from "@/components/shared/MenuBar";
import NextTopLoader from "nextjs-toploader";
import Sidebar from "@/components/shared/Sidebar";
import { SWRProvider } from "@/components/swr-provider";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "SquareEdge | Sell with confidence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <NextTopLoader />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SWRProvider>
            <MenuBar />
            <div className="flex h-screen border-collapse overflow-hidden">
              <Sidebar />
              <main className="overflow-auto justify-center flex w-full mx-auto pb-4 px-4 md:px-6">
                <div className="w-full md:max-w-6xl py-32">{children}</div>
              </main>
            </div>
          </SWRProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
