import "./video.css";
import "../globals.css"
export const metadata = {
  title: "SquareEdge | Sell with confidence",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
